### ISSUE TITLE
contao 3.2 - Backend error ?

### ISSUE THREAD

**Issue by extractjan** [cliffparnitzky-archive/EfgMemberSelect#6]
Beim Bearbeiten von gespeicherten EFG-Formulardaten im Backend erscheint beim Speichern die Fehlermeldung "Ungültige Eingabe: 7". (7 ist die Member-Id). 

Gleicher Fehler, egal ob Member-ID oder Member-Name als Rückgabewert gewählt ist.

Im Frontend funktioniert alles.

festgestellt unter Contao 3.2.14 
EfgMemberSelect     2.0.1   Build 11

**Comment by cliffparnitzky** [comment]
Seit Contao 3.0.x wird bei der Validierung der Formularfeldeingaben zusätzlich die Methode [`isValidOption`](https://github.com/contao/core/blob/master/system/modules/core/forms/FormSelectMenu.php#L136) aufgerufen. Diese muss in `FormMemberSelectMenu` überschrieben werden um auf die validen Mitglieder zu prüfen.

**Comment by cliffparnitzky** [comment]
fixed in [version 2.0.2](https://github.com/cliffparnitzky/EfgMemberSelect/releases/tag/2.0.2)

**Comment by extractjan** [comment]
Erstmal Vielen Dank! 
Aber ich glaube der Fehler besteht noch immer bei Mehrfachauswahl.

**Comment by cliffparnitzky** [comment]
Okay, werde ich nochmal prüfen

**Comment by cliffparnitzky** [comment]
Fix ist in [version 2.0.2](https://github.com/cliffparnitzky/EfgMemberSelect/releases/tag/2.0.2) drin.

@extractjan kannst bitte noch mal testen?

**Comment by extractjan** [comment]
getestet, fehlerfrei!

**Comment by cliffparnitzky** [comment]
Top, danke
